### ISSUE TITLE
Cant install vknplayer

### ISSUE THREAD

**Issue by brbrr** [kicumkicum/vknplayer#17]
When installing app from npm package or sources get same error (raspberry PI 1 B+)
[npm-debug.log](http://paste.org.ru/?tc5kse) 

Error:
make: Leaving directory '/home/pi/node_modules/vknplayer/node_modules/lame/build'
npm ERR! Linux 3.18.14+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "vknplayer"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! path /home/pi/node_modules/vknplayer/node_modules/nclosure/bin\closure.json
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/home/pi/node_modules/vknplayer/node_modules/nclosure/bin\closure.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by kicumkicum** [comment]
oops.. node v0.10.x need

**Comment by brbrr** [comment]
Yes, downgrading to 0.10.36 fixed this problem. Thanks!

**Comment by kicumkicum** [comment]
good :smile_cat:
