### ISSUE TITLE
volume control from player app

### ISSUE THREAD

**Issue by brbrr** [kicumkicum/vknplayer#20]
Volume control could be every useful when using vknp on external devices such as RPi

**Comment by kicumkicum** [comment]
done in develop. release - v0.0.42

**Comment by brbrr** [comment]
It's works OK now, thanks. what step value is used? for me it's quite small, so I need to push `f8` for a while to have some significant changes.
This is for  RPI B+ over ssh

**Comment by kicumkicum** [comment]
Step was 5%. Yestarday I set it 10%.
