### ISSUE TITLE
Add console command to set volume level

### ISSUE THREAD

**Issue by brbrr** [kicumkicum/vknplayer#35]
add functionality to set volume from console. 
this is useful as f\* buttons are quite laggy

`volume` - return current vol level
`volume 50` - set vol level to 50%
`volume 0` - mute

Than this could be used for visual slider (as in alsamixer)

**Comment by kicumkicum** [comment]
ok. @brbrr you test volume change in develop branch?
I want feedback :smile_cat:

**Comment by brbrr** [comment]
yup @kicumkicum 
I've add comment to related ticket ;)
